name: echogram
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - argcomplete
  - bottleneck
  - cmocean
  - conda-build
  - dask=2025.5.1
  - echopype=0.10.1
  - h5netcdf
  - hvplot
  - ipykernel
  - ipywidgets
  - libnetcdf
  - matplotlib
  - netcdf4
  - numpy
  - pandas=2.3.1
  - pillow
  - pip
  - python-dateutil
  - python-wget
  - tqdm
  - xarray
